version: "5"

services:
  web-app:
    build: .
    environment:
      - DOCKER=1
    env_file:
      - ./.docker.env
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn app.main:create_app --host 0.0.0.0"
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8

  redis:
    image: redis:5

  celery:
    build: .
    command: celery -A app.tasks.worker.celery worker --loglevel=info --logfile=app/logs/celery.log
    environment:
      - DOCKER=1
    env_file:
      - ./.docker.env
    depends_on:
      - web-app
      - redis
