"""empty message

Revision ID: 626b25776f76
Revises: 
Create Date: 2023-07-19 23:03:01.892133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626b25776f76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('current_page', sa.Integer(), nullable=True),
    sa.Column('time_opened', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_url', sa.String(length=255), nullable=True),
    sa.Column('cover_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
